export { createRecorder } from './recorder'
export type { Recorder, RecorderOptions } from './recorder'
export { Mirror } from './mirror'
export { serializeDocument, serializeSubtree, absoluteUrl } from './snapshot'
export type { SerializeOptions } from './snapshot'
export { MutationCollector } from './observer'
export { buildSelector, describeElement, interactiveAncestor, elementText } from './selector'
export { RageClickDetector, throttle } from './autocapture'
export { isMasked, maskText, MASK_ATTR, MASK_CHAR } from './mask'
export { NodeKind } from './types'
export type * from './types'
